In [1]:
#import datasetBuilder
import tests
import importlib
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from importlib import reload
import math_distance
import spectral_similarity
import pandas as pd
import datasetBuilder



In [2]:
reload(datasetBuilder)
target=datasetBuilder.get_target_df("C:\\Users\\jonah\\School\\specent\\nist_out.MSP")

In [3]:
reload(datasetBuilder)
matches = datasetBuilder.create_matches_df(target, 10,10,10)

In [88]:
reload(spectral_similarity)
reload(datasetBuilder)
matches=matches.dropna(how='any')
sim_methods = ['lorentzian','max_entropy','squared_chord','lorentzian_jonah','rbf','perc_peaks_in_common','ave_bhattacharya_2','max_bhattacharya_2']
clean, mod = datasetBuilder.create_model_dataset(matches, sim_methods = [sim_methods[0]], noise_threshes=[0.01,0.5])

In [90]:
mod

cequery  isvquery  cetarget  isvtarget  cgsame  instsame  cesame  isvsame  \
0     30.0      34.0      -1.0       16.0     0.0       0.0     0.0      0.0   
1     30.0      34.0      30.0       24.0     1.0       1.0     0.0      1.0   
2     30.0      34.0      -1.0       90.0     0.0       0.0     0.0      0.0   
3     30.0      34.0      -1.0       -1.0     0.0       0.0     0.0      0.0   
4     30.0      34.0      -1.0       48.0     0.0       0.0     0.0      0.0   
5     30.0      34.0      30.0       40.0     1.0       1.0     0.0      1.0   
6     30.0      34.0      30.0       28.0     1.0       1.0     0.0      1.0   
7     30.0      34.0      30.0       32.0     1.0       1.0     0.0      1.0   
8     30.0      34.0      -1.0       62.0     0.0       0.0     0.0      0.0   
9     30.0      34.0      -1.0       30.0     0.0       0.0     0.0      0.0   

   isvratio   ceratio  ...  query_ent_change_0.5_1_0.05da_0.05da  \
0       0.0  2.125000  ...                              2.132478   
1       1.0  1.416667  ...                              2.132478   
2       0.0  2.647059  ...                              2.132478   
3       0.0  0.000000  ...                              2.132478   
4       0.0  1.411765  ...                              2.132478   
5       1.0  1.176471  ...                              2.132478   
6       1.0  1.214286  ...                              2.132478   
7       1.0  1.062500  ...                              2.132478   
8       0.0  1.823529  ...                              2.132478   
9       0.0  1.133333  ...                              2.132478   

   query_peaks_change_0.5_1_0.05da_0.05da  \
0                                     194   
1                                     194   
2                                     194   
3                                     194   
4                                     194   
5                                     194   
6                                     194   
7                                     194   
8                                     194   
9                                     194   

   query_normal_ent_change_0.5_1_0.05da_0.05da  \
0                                     -0.36963   
1                                     -0.36963   
2                                     -0.36963   
3                                     -0.36963   
4                                     -0.36963   
5                                     -0.36963   
6                                     -0.36963   
7                                     -0.36963   
8                                     -0.36963   
9                                     -0.36963   

   query_mass_change_0.5_1_0.05da_0.05da  \
0                               -6208.22   
1                               -6208.22   
2                               -6208.22   
3                               -6208.22   
4                               -6208.22   
5                               -6208.22   
6                               -6208.22   
7                               -6208.22   
8                               -6208.22   
9                               -6208.22   

   target_ent_change_0.5_1_0.05da_0.05da  \
0                               0.750310   
1                               2.526673   
2                               1.918309   
3                               0.785139   
4                               2.851020   
5                               3.189249   
6                               1.851830   
7                               2.085309   
8                               2.674434   
9                               2.258651   

   target_peaks_change_0.5_1_0.05da_0.05da  \
0                                        9   
1                                      154   
2                                       39   
3                                       14   
4                                       72   
5                                      172   
6                                 

In [59]:
a=[1]
b=[2]

len((a+b))

2

In [20]:
spectral_similarity.multiple_similarity(matches.iloc[7]['query'], matches.iloc[3]['target'],methods=['perc_peaks_in_common', 'lorentzian'], ms2_da=0.05, need_normalize_result=False)

[[ 50.0149   0.      89.11  ]
 [ 51.0227   0.     193.31  ]
 [ 53.0385   0.      35.26  ]
 [ 55.0176   0.      56.84  ]
 [ 63.0227   0.      40.26  ]
 [ 65.0386   4.3    816.28  ]
 [ 67.054    0.      40.86  ]
 [ 68.9968   0.      43.36  ]
 [ 75.0226   0.      17.88  ]
 [ 77.0383   0.     490.91  ]
 [ 78.0461   0.      12.29  ]
 [ 79.0541   9.29    31.37  ]
 [ 81.0332   0.      31.17  ]
 [ 89.0384   0.      59.54  ]
 [ 90.0462   0.       9.89  ]
 [ 91.0541 999.     999.    ]
 [ 95.049    0.     272.33  ]
 [102.0463   0.      63.04  ]
 [103.0542  11.79   321.28  ]
 [105.0335   0.      40.06  ]
 [107.0491  74.63    64.34  ]
 [115.0543  19.48   250.85  ]
 [119.0491   2.9     26.07  ]
 [127.0545   0.      35.36  ]
 [128.062    0.     144.16  ]
 [129.0699   6.99     0.    ]
 [131.0493  18.78    27.57  ]
 [139.0547   0.      37.66  ]
 [141.07    23.28    29.37  ]
 [147.0441   2.4     18.48  ]
 [151.0543   0.      52.85  ]
 [152.0621  15.88   559.54  ]
 [153.0698  15.08   329.47  ]
 [154.0778

{'perc_peaks_in_common': 0.5, 'lorentzian': -245.90597910280354}

In [54]:
import tools
3/len(tools.match_peaks_in_spectra(matches.iloc[0]['query'], matches.iloc[0]['target'], ms2_da=0.05))

0.13043478260869565

In [64]:
a=np.array([1,2])
b=np.array([2,3])
np.sum(np.log(1+np.abs(a-b)))

1.3862943611198906

In [28]:


noise_thresholds=[0.01]
centroid_values = [0.05]

target = datasetBuilder.get_target_df_with_noise("C:\\Users\\jonah\\School\\specent\\nist_out.MSP", noise_thresholds, centroid_values, std=5, lam=3)






ValueError: too many values to unpack (expected 2)

In [ ]:
import math
np.log(math.e**3/math.e**4)

-1.0

In [ ]:
5**(-3)==1/125

True

In [36]:
a=pd.DataFrame([[1,2,3],[4,5,6]])
a.columns=[1,2,3]

def add23(boop, bop, bip):


    return np.array([boop+bop+bip,5])

yool= a.apply(lambda x: add23(x[2],x[3], bip=4), axis=1, result_type='expand')

yool

0  1
0   9  5
1  15  5

In [54]:
a

1  2  3
0  1  2  3
1  4  5  6

In [ ]:
reload(datasetBuilder)
print(yool)
for i in range(1000):
    datasetBuilder.add_poisson_noise_to_spectrum(yool, precursor_mz = 4, noise_peaks = 2, lam=3)
    
print(yool)

[[ 1.         57.03263588]
 [ 1.         22.83363926]
 [ 2.         68.70773311]
 [ 3.         49.06675156]
 [ 4.         22.2741793 ]]
[[ 1.         57.03263588]
 [ 1.         22.83363926]
 [ 2.         68.70773311]
 [ 3.         49.06675156]
 [ 4.         22.2741793 ]]


In [ ]:
noise_thresholds=[0.0,0.01,0.05,0.1,0.2]
centroid_values = [0.01,0.05,0.1]

target = datasetBuilder.get_target_df("C:\\Users\\jonah\\School\\specent\\nist_out.MSP", noise_thresholds, centroid_values)
target=target.sample(frac=1)

In [ ]:
mod_dataset = datasetBuilder.create_model_dataset(target, 10, sim_methods = ['lorentzian','max_entropy','squared_chord','lorentzian_jonah','rbf','perc_peaks_in_common','ave_bhattacharya_2','max_bhattacharya_2'], limit_rows=2000000)
mod_dataset.to_csv("C:\\Users\\jonah\\projects\\SpecSim\\mod_dataset_powers.csv")

Used 37699 entries to create Training Set of 2000048 rows


In [ ]:
res_dict = tests.run_all_comparisons(target, lim_rows=20000)
df_res = tests.dict_to_df(res_dict)
df_res.to_csv("C:\\Users\\jonah\\projects\\SpecSim\\allsim_res_3.csv")

examined 0 rows
examined 1000 rows
examined 2000 rows
examined 3000 rows
examined 4000 rows
examined 5000 rows
examined 6000 rows
examined 7000 rows
examined 8000 rows
examined 9000 rows
examined 10000 rows
examined 11000 rows
examined 12000 rows
examined 13000 rows
examined 14000 rows
examined 15000 rows
examined 16000 rows
examined 17000 rows
examined 18000 rows
examined 19000 rows


In [ ]:
noise_thresholds=[0.05]
centroid_values = [0.05]

target = datasetBuilder.get_target_df("C:\\Users\\jonah\\School\\specent\\nist_out.MSP", noise_thresholds, centroid_values)
target=target.sample(frac=1)

In [34]:
reload(math_distance)
res_dict = tests.run_all_comparisons(target, lim_rows=20000)
df_res = tests.dict_to_df(res_dict)
df_res.to_csv("C:\\Users\\jonah\\projects\\SpecSim\\allsim_res_full.csv")

examined 0 rows
examined 1000 rows
examined 2000 rows
examined 3000 rows
examined 4000 rows
examined 5000 rows
examined 6000 rows
examined 7000 rows
examined 8000 rows
examined 9000 rows
examined 10000 rows
examined 11000 rows
examined 12000 rows
examined 13000 rows
examined 14000 rows
examined 15000 rows
examined 16000 rows
examined 17000 rows
examined 18000 rows
examined 19000 rows


In [ ]:
df_res = tests.dict_to_df(res_dict)
df_res.to_csv("C:\\Users\\jonah\\projects\\SpecSim\\allsim_res_2.csv")

In [29]:
import spectral_similarity

sims=list()
for i in spectral_similarity.methods_range:
    sims.append(i)
    sims.append('max_'+i)
    sims.append('min_'+i)
    sims.append('ave_'+i)
    
mod_data = datasetBuilder.create_model_dataset(target, 10, sims, 10, nonspec_features=False, spec_features=False)

Used 1 entries to create Training Set of 176 rows


In [30]:
mod_data=mod_data.iloc[:,1:]
mod_data.columns=sims
mod_data

entropy_jonah  max_entropy_jonah  min_entropy_jonah  ave_entropy_jonah  \
0         0.913638                1.0           0.956819       8.503036e-01   
1         0.515401                1.0           0.757701       1.594261e-01   
2         0.000000                0.0           0.000000       0.000000e+00   
3         0.492044                1.0           0.746022       1.465877e-01   
4         0.000000                0.0           0.000000       0.000000e+00   
..             ...                ...                ...                ...   
171       0.000000                0.0           0.000000       1.110223e-16   
172       0.000000                0.0           0.000000       0.000000e+00   
173       0.000000                0.0           0.000000       0.000000e+00   
174       0.545849                1.0           0.772925       2.775939e-01   
175       0.180949                1.0           0.590474       4.186394e-03   

     lorentzian_jonah  max_lorentzian_jonah  min_lorentzian_jonah  \
0            0.850304                   1.0              0.925152   
1            0.159426                   1.0              0.579713   
2            0.000000                   0.0              0.000000   
3            0.146588                   1.0              0.573294   
4            0.000000                   0.0              0.000000   
..                ...                   ...                   ...   
171          0.000000                   0.0              0.000000   
172          0.000000                   0.0              0.000000   
173          0.000000                   0.0              0.000000   
174          0.277594                   1.0              0.638797   
175          0.004186                   1.0              0.502093   

     ave_lorentzian_jonah   entropy  max_entropy  ...  min_ruzicka  \
0            9.417870e-01  0.941787     1.000000  ...     0.899555   
1            3.633000e-01  0.363300     1.000000  ...     0.549398   
2            0.000000e+00  0.278652     0.278652  ...     0.000000   
3            3.422636e-01  0.342264     1.000000  ...     0.544847   
4            0.000000e+00  0.278652     0.278652  ...     0.000000   
..                    ...       ...          ...  ...          ...   
171          0.000000e+00  0.278652     0.278652  ...     0.000000   
172          3.330669e-16  0.278652     0.278652  ...     0.000000   
173          0.000000e+00  0.278652     0.278652  ...     0.000000   
174          5.179659e-01  0.517966     1.000000  ...     0.592020   
175          2.080701e-02  0.020807     1.000000  ...     0.501128   

     ave_ruzicka   roberts  max_roberts  min_roberts  ave_roberts  \
0       0.838743  0.838743          1.0     0.919372     0.888340   
1       0.106081  0.106081          1.0     0.553040     0.179825   
2       0.000000  0.000000          0.0     0.000000     0.000000   
3       0.095861  0.095861          1.0     0.547930     0.164621   
4       0.000000  0.000000          0.0     0.000000     0.000000   
..           ...       ...          ...          ...          ...   
171     0.000000  0.000000          0.0     0.000000     0.000000   
172     0.000000  0.000000          0.0     0.000000     0.000000   
173     0.000000  0.000000          0.0     0.000000     0.000000   
174     0.203754  0.203754          1.0     0.601877     0.310869   
175     0.002262  0.002262          1.0     0.501131     0.004503   

     intersection  max_intersection  min_intersection  ave_intersection  
0        0.888340               1.0          0.944170               0.0  
1        0.179825               1.0          0.589912               0.0  
2        0.000000               0.0          0.000000               0.0  
3        0.164621               1.0          0.582311               0.0  
4        0.000000               0.0          0.000000               0.0  
..            ...               ...               ...               ...  
171      0.000000               0.0    

In [21]:
import scipy.stats
scipy.stats.entropy([1 for i in range(10000)])

9.21034037197618

In [39]:
import numpy as np
import plotAndOrderResults

In [43]:
import pandas as pd
df_res=pd.read_csv("C:\\Users\\jonah\\projects\\SpecSim\\allsim_res_4.csv")

In [44]:
plotAndOrderResults.add_evals_to_df(df_res)

Unnamed: 0            metric  true_pos  false_pos  true_neg  \
0                0     entropy_jonah  402218.0   655921.0    1582.0   
1                1     entropy_jonah  378866.0   596894.0   60609.0   
2                2     entropy_jonah  378786.0   596742.0   60761.0   
3                3     entropy_jonah  378739.0   596520.0   60983.0   
4                4     entropy_jonah  378638.0   596171.0   61332.0   
...            ...               ...       ...        ...       ...   
191995      191995  ave_intersection   30398.0     3717.0  653786.0   
191996      191996  ave_intersection   30264.0     3701.0  653802.0   
191997      191997  ave_intersection   30142.0     3669.0  653834.0   
191998      191998  ave_intersection   30018.0     3651.0  653852.0   
191999      191999  ave_intersection       0.0        0.0  657503.0   

        false_neg       tpr       fpr       tnr       fdr  precision       npv  
0           789.0  0.998042  0.997594  0.002406  0.619882   0.380118  0.667229  
1         24141.0  0.940098  0.907819  0.092181  0.611722   0.388278  0.715150  
2         24221.0  0.939899  0.907588  0.092412  0.611712   0.388288  0.714987  
3         24268.0  0.939783  0.907251  0.092749  0.611653   0.388347  0.715335  
4         24369.0  0.939532  0.906720  0.093280  0.611577   0.388423  0.715651  
...           ...       ...       ...       ...       ...        ...       ...  
191995   372609.0  0.075428  0.005653  0.994347  0.108955   0.891045  0.636973  
191996   372743.0  0.075095  0.005629  0.994371  0.108965   0.891035  0.636896  
191997   372865.0  0.074793  0.005580  0.994420  0.108515   0.891485  0.636831  
191998   372989.0  0.074485  0.005553  0.994447  0.108438   0.891562  0.636761  
191999   403007.0  0.000000  0.000000  1.000000       NaN        NaN  0.619988  

[192000 rows x 12 columns]

In [42]:
plotAndOrderResults.order_criterion_from_df(df_res)

[('lorentzian', 0.7300641804071316),
 ('ave_bhattacharya_2', 0.7208769951059095),
 ('max_fidelity', 0.7180751544062873),
 ('bhattacharya_1', 0.7173760922199357),
 ('fidelity', 0.7173756494726958),
 ('bhattacharya_2', 0.7173752688927499),
 ('squared_chord', 0.7172083314447361),
 ('matusita', 0.7172057013676244),
 ('harmonic_mean', 0.7171287009889982),
 ('max_bhattacharya_2', 0.7170978106623571),
 ('chi2', 0.7168639397779886),
 ('ave_entropy', 0.7167681871140495),
 ('probabilistic_symmetric_chi_squared', 0.7166572003091066),
 ('max_entropy', 0.7165492499766484),
 ('ave_fidelity', 0.716289439957774),
 ('cross_ent', 0.7159205865659797),
 ('max_probabilistic_symmetric_chi_squared', 0.7157269431735657),
 ('max_harmonic_mean', 0.7157265280854381),
 ('max_chi2', 0.7157257116629581),
 ('max_cross_ent', 0.715710405432143),
 ('lorentzian_jonah', 0.7152156924202139),
 ('ruzicka', 0.7151548262097601),
 ('motyka', 0.7151473960747221),
 ('braycurtis', 0.7151473951193057),
 ('ave_squared_chord', 0.714

In [45]:
plotAndOrderResults.order_criterion_from_df(df_res)

[('lorentzian', 0.7338696176293988),
 ('squared_chord', 0.7227148578491224),
 ('matusita', 0.722713602912452),
 ('bhattacharya_1', 0.7223760609321797),
 ('fidelity', 0.7223759261117116),
 ('bhattacharya_2', 0.7223755720129197),
 ('chi2', 0.7216616787572258),
 ('ave_fidelity', 0.7215291130227008),
 ('ave_common_mass', 0.7215079714641035),
 ('common_mass', 0.7215063119811161),
 ('probabilistic_symmetric_chi_squared', 0.7214717317452944),
 ('ave_cross_ent', 0.7214668630392762),
 ('harmonic_mean', 0.7213299155423598),
 ('ave_bhattacharya_2', 0.7212423357877497),
 ('cross_ent', 0.7209967304148932),
 ('max_fidelity', 0.7208219896040915),
 ('max_cross_ent', 0.7206145883919526),
 ('ave_entropy', 0.7199627131931543),
 ('max_common_mass', 0.7196667984160168),
 ('manhattan', 0.719619620596337),
 ('max_chi2', 0.7195797827170047),
 ('max_probabilistic_symmetric_chi_squared', 0.7195788057804454),
 ('max_harmonic_mean', 0.7195776562222108),
 ('lorentzian_jonah', 0.7195071113070715),
 ('absolute_value

TypeError: create_model_dataset() missing 2 required positional arguments: 'target_df' and 'precursor_mass_thresh'

In [8]:
yool = spectral_similarity.multiple_similarity(b,a, ms2_da=0.05, methods=['max_lorentzian','reverse_lorentzian'])

In [10]:
yool['reverse_lorentzian']

0.0

In [11]:
a

array([[ 41.04,  49.15],
       [ 41.06,  10.39],
       [ 43.02,  23.08],
       [ 43.06, 999.  ],
       [ 44.05, 148.55],
       [ 55.06,  54.05],
       [ 56.05, 412.19],
       [ 57.03,  20.18],
       [ 57.07,  45.95],
       [ 67.06,  35.56],
       [ 69.  ,  88.31],
       [ 69.07,  42.66],
       [ 70.03,  25.47],
       [ 71.01, 123.08],
       [ 71.09, 912.29],
       [ 74.02, 328.07],
       [ 74.06, 684.81],
       [ 81.07,  37.96],
       [ 84.04, 161.94],
       [ 85.03,  53.25],
       [ 95.09,  48.05],
       [ 98.06,  82.42],
       [ 99.04,  84.91],
       [ 99.08, 288.01],
       [102.06, 714.48],
       [113.06,  20.98],
       [141.09, 467.83]])

In [12]:
b[]

array([[171.0446,   5.29  ],
       [288.078 ,   1.7   ],
       [289.0869, 999.    ],
       [290.0902,   5.09  ]])

In [167]:
yool['reverse_entropy']

-0.10161687761510674

In [101]:
match = tools.match_peaks_in_spectra(a,b, ms2_da=0.05)

In [117]:
import math_distance

In [119]:
math_distance._select_common_peaks(a,b)

IndexError: boolean index did not match indexed array along dimension 0; dimension is 8 but corresponding boolean dimension is 17

In [122]:
yool = a>0

In [123]:
yool

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])